from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

NAVY = colors.HexColor("#0f172a")
GREEN = colors.HexColor("#16a34a")
AMBER = colors.HexColor("#d97706")
RED = colors.HexColor("#dc2626")
LIGHT_GRAY = colors.HexColor("#f8fafc")
MID_GRAY = colors.HexColor("#e2e8f0")
TEXT_GRAY = colors.HexColor("#475569")
TEXT_DARK = colors.HexColor("#0f172a")
WHITE = colors.white
BLUE = colors.HexColor("#2563eb")

DISCLAIMER = (
    "This report was generated by PropIQ using publicly available data from Zillow, EPA AirNow, "
    "BLS, FEMA, and other sources. It is intended for research and informational purposes only "
    "and does not constitute financial, legal, tax, insurance, or investment advice. "
    "Always consult a licensed real estate professional before making investment decisions. "
    "Scores are model-generated estimates and may not reflect current market conditions."
)

# ── Agent reasoning definitions ──────────────────────────────────────────────
AGENT_META = {
    "price_score": {
        "label": "Price Agent",
        "source": "Zillow ZHVI CSV",
        "measured": "12-month % price change vs national average",
        "low": "Price declining or growing below 2%",
        "mid": "Growing 2-4% (near national average)",
        "high": "Growing 4%+ (above national average)",
        "impact": "Higher score = better capital gains potential",
    },
    "neighborhood_score": {
        "label": "Neighborhood Agent",
        "source": "Google Places + Census ACS",
        "measured": "School ratings, crime index, walkability. Formula: 40% schools + 30% safety + 30% walkability",
        "low": "Poor schools, high crime, car dependent",
        "mid": "Average neighborhood quality",
        "high": "Good schools, safe, walkable",
        "impact": "Higher score = stronger rental demand",
    },
    "rental_yield": {
        "label": "Rental Yield Agent",
        "source": "Zillow ZORI Rent CSV",
        "measured": "Gross rental yield = (monthly_rent x 12 / price) x 100",
        "low": "Yield below 4% (poor cash flow)",
        "mid": "Yield 4-7% (average)",
        "high": "Yield above 7% (strong cash flow)",
        "impact": "Higher score = better monthly income",
    },
    "forecast_score": {
        "label": "Forecast Agent",
        "source": "Zillow 24-month price history",
        "measured": "ML LinearRegression price prediction for next 12 months",
        "low": "Price expected to decline",
        "mid": "Price expected to stay flat or grow slowly",
        "high": "Price expected to grow significantly",
        "impact": "Higher score = better future returns",
    },
    "aqi_score": {
        "label": "AQI Agent",
        "source": "EPA AirNow API",
        "measured": "Current Air Quality Index (AQI 0-500). Formula: score = 100 - min(AQI, 100)",
        "low": "Unhealthy air (AQI 60+)",
        "mid": "Moderate air quality (AQI 30-60)",
        "high": "Good air quality (AQI below 30)",
        "impact": "Higher score = healthier living environment",
    },
    "pollen_score": {
        "label": "Pollen Agent",
        "source": "Google Pollen API",
        "measured": "Tree, grass, weed pollen combined index. 1 in 4 Americans has seasonal allergies.",
        "low": "Very high pollen (severe allergy risk)",
        "mid": "Moderate pollen levels",
        "high": "Low pollen (allergy-friendly area)",
        "impact": "Higher score = better for allergy sufferers",
    },
    "airbnb_score": {
        "label": "Airbnb STR Agent",
        "source": "Inside Airbnb market data",
        "measured": "Short-term rental yield vs long-term. STR yield = (365 - vacancy) x nightly_rate / price",
        "low": "STR yield below LTR (better to rent long-term)",
        "mid": "STR slightly better than LTR",
        "high": "STR significantly outperforms LTR",
        "impact": "Higher score = Airbnb more profitable",
    },
    "climate_risk_score": {
        "label": "Climate Risk Agent",
        "source": "FEMA NFHL flood maps",
        "measured": "Flood zone, wildfire risk, extreme heat days. Higher score = LOWER risk (inverted scale).",
        "low": "High risk (flood zone A/AE or wildfire zone)",
        "mid": "Moderate risk",
        "high": "Low risk (FEMA Zone X, minimal flood risk)",
        "impact": "Higher score = safer investment long-term",
    },
}

# Map display labels to keys for lookup
_LABEL_TO_KEY = {v["label"].lower().replace(" agent", "").strip(): k for k, v in AGENT_META.items()}
_LABEL_TO_KEY.update({
    "price momentum": "price_score",
    "price": "price_score",
    "neighborhood": "neighborhood_score",
    "rental yield": "rental_yield",
    "forecast": "forecast_score",
    "aqi": "aqi_score",
    "air quality": "aqi_score",
    "pollen": "pollen_score",
    "airbnb str": "airbnb_score",
    "airbnb": "airbnb_score",
    "climate risk": "climate_risk_score",
    "climate": "climate_risk_score",
})


def _estimate_metrics(scores: dict, property_details: dict) -> dict:
    """Calculate yield estimates from agent scores, or real values if available."""
    rental_score = float(scores.get("rental_yield", 50))
    airbnb_score = float(scores.get("airbnb_score", 50))
    price_score = float(scores.get("price_score", 50))
    forecast = float(scores.get("forecast_score", 50))

    # Try to compute real yields from asking price + rent
    asking = (property_details.get("price")
              or property_details.get("asking_price")
              or property_details.get("asking_price_display")
              or 0)
    monthly_rent = (property_details.get("monthly_rent")
                    or property_details.get("estimated_rent")
                    or property_details.get("estimated_rent_display")
                    or 0)
    try:
        asking = float(str(asking).replace("$", "").replace(",", ""))
    except (ValueError, TypeError):
        asking = 0
    try:
        monthly_rent = float(str(monthly_rent).replace("$", "").replace(",", "").replace("/mo", ""))
    except (ValueError, TypeError):
        monthly_rent = 0

    if asking > 0 and monthly_rent > 0:
        gross_yield = round((monthly_rent * 12 / asking) * 100, 1)
        str_yield = round(gross_yield * 1.5, 1)  # STR typically 1.5x LTR
        ltr_yield = gross_yield
        annual_return = round(gross_yield + price_score * 0.08, 1)
        estimated = False
    else:
        # Reverse-engineer from scores: score = (yield/8) * 100 -> yield = score*8/100
        gross_yield = round(rental_score * 8 / 100, 1)
        str_yield = round(airbnb_score * 8 / 100, 1)
        ltr_yield = gross_yield
        annual_return = round(
            (gross_yield * 0.5) + (price_score * 0.08) + (forecast * 0.04), 1
        )
        estimated = True

    return {
        "gross_yield": f"{gross_yield}%",
        "str_yield": f"{str_yield}%",
        "ltr_yield": f"{ltr_yield}%",
        "annual_return": f"~{annual_return}%" if estimated else f"{annual_return}%",
        "estimated": estimated,
    }


def _badge_color(recommendation: str) -> colors.Color:
    if recommendation == "BUY":
        return GREEN
    if recommendation == "HOLD":
        return AMBER
    return RED


def _score_color(score: float) -> colors.Color:
    if score >= 70:
        return GREEN
    if score >= 40:
        return AMBER
    return RED


def _score_meaning(score: float, meta: dict) -> str:
    """Return a short meaning string based on score bracket."""
    if score < 40:
        return meta["low"]
    if score <= 70:
        return meta["mid"]
    return meta["high"]


def _score_bracket_label(score: float) -> str:
    if score >= 70:
        return "Above average"
    if score >= 40:
        return "Average"
    return "Below average"


def _find_agent_key(label: str) -> str | None:
    """Find the AGENT_META key from a score_row label."""
    normalized = label.lower().strip()
    for search_label, key in _LABEL_TO_KEY.items():
        if search_label in normalized or normalized in search_label:
            return key
    return None


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("H1", parent=base["Title"], fontSize=22, textColor=WHITE, leading=28, spaceAfter=4),
        "h2": ParagraphStyle("H2", parent=base["Heading1"], fontSize=14, textColor=NAVY, leading=18, spaceBefore=6, spaceAfter=4),
        "h3": ParagraphStyle("H3", parent=base["Heading2"], fontSize=11, textColor=NAVY, leading=14, spaceBefore=4, spaceAfter=2),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=9.5, leading=14, textColor=TEXT_DARK),
        "small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=8, leading=11, textColor=TEXT_GRAY),
        "label": ParagraphStyle("Label", parent=base["BodyText"], fontSize=8, leading=10, textColor=TEXT_GRAY, spaceAfter=1),
        "tagline": ParagraphStyle("Tagline", parent=base["BodyText"], fontSize=11, leading=14, textColor=colors.HexColor("#94a3b8")),
        "badge": ParagraphStyle("Badge", parent=base["BodyText"], fontSize=18, leading=22, textColor=WHITE, alignment=1),
        "score_big": ParagraphStyle("ScoreBig", parent=base["Title"], fontSize=42, textColor=WHITE, leading=48, alignment=1),
        "white_body": ParagraphStyle("WhiteBody", parent=base["BodyText"], fontSize=9.5, leading=13, textColor=WHITE),
        "section_label": ParagraphStyle("SLabel", parent=base["BodyText"], fontSize=7.5, leading=10, textColor=TEXT_GRAY, spaceAfter=1, fontName="Helvetica-BoldOblique"),
        "bullet": ParagraphStyle("Bullet", parent=base["BodyText"], fontSize=9.5, leading=14, textColor=TEXT_DARK, leftIndent=12, bulletIndent=0),
    }


def _page_header(elements: list, title: str, subtitle: str = "") -> None:
    header_data = [[Paragraph("<b>PropIQ</b>", ParagraphStyle("logo", fontSize=13, textColor=WHITE, fontName="Helvetica-Bold")),
                    Paragraph(title, ParagraphStyle("hdr", fontSize=10, textColor=colors.HexColor("#94a3b8"), alignment=2))]]
    t = Table(header_data, colWidths=[3.5 * inch, 4.3 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.18 * inch))


def _divider(elements: list) -> None:
    elements.append(HRFlowable(width="100%", thickness=1, color=MID_GRAY, spaceAfter=8, spaceBefore=6))


def build_pdf_report(
    property_details: dict[str, Any],
    score_rows: list[dict[str, Any]],
    report_text: str,
    recommendation: str,
    weighted_total: float,
    user_name: str = "PropIQ User",
    generated_at: str | None = None,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )
    s = _styles()
    address = property_details.get("address") or f"ZIP {property_details.get('zip_code', 'N/A')}"
    zip_code = property_details.get("zip_code", "N/A")
    gen_date = generated_at or datetime.now().strftime("%Y-%m-%d %H:%M")
    badge_color = _badge_color(recommendation)
    score_color = _score_color(weighted_total)

    elements: list[Any] = []

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 1: COVER
    # ══════════════════════════════════════════════════════════════════════════
    cover_top = Table(
        [[Paragraph("<b>PropIQ</b>", ParagraphStyle("clogo", fontSize=20, textColor=WHITE, fontName="Helvetica-Bold")),
          Paragraph("Real Estate Intelligence. Unbiased.", ParagraphStyle("ctagline", fontSize=10, textColor=colors.HexColor("#94a3b8"), alignment=2))]],
        colWidths=[3.5 * inch, 4.3 * inch],
    )
    cover_top.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(cover_top)
    elements.append(Spacer(1, 0.3 * inch))

    # Score hero panel
    score_panel_data = [[
        Paragraph(f"{weighted_total:.1f}", s["score_big"]),
        Paragraph("/100", ParagraphStyle("slash", fontSize=16, textColor=colors.HexColor("#94a3b8"), leading=22, alignment=1)),
        Paragraph(recommendation, ParagraphStyle("rec", fontSize=16, textColor=WHITE, leading=22, fontName="Helvetica-Bold", alignment=1)),
    ]]
    score_panel = Table(score_panel_data, colWidths=[2.5 * inch, 1.0 * inch, 4.3 * inch])
    score_panel.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (1, 0), score_color),
        ("BACKGROUND", (2, 0), (2, 0), badge_color),
        ("TOPPADDING", (0, 0), (-1, -1), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(score_panel)
    elements.append(Spacer(1, 0.25 * inch))

    # Property info box
    info_data = [
        [Paragraph("<b>PROPERTY ADDRESS</b>", s["label"]), ""],
        [Paragraph(address, ParagraphStyle("addr", fontSize=14, textColor=NAVY, fontName="Helvetica-Bold", leading=18)), ""],
        [Paragraph(f"ZIP Code: {zip_code}", s["body"]), Paragraph(f"Analysis Date: {gen_date[:10]}", ParagraphStyle("date", fontSize=9.5, leading=14, textColor=TEXT_DARK, alignment=2))],
        [Paragraph(f"Property Type: {property_details.get('property_type', 'N/A')}", s["body"]),
         Paragraph(f"Generated for: {user_name}", ParagraphStyle("gen", fontSize=9.5, leading=14, textColor=TEXT_DARK, alignment=2))],
    ]
    info_table = Table(info_data, colWidths=[4.5 * inch, 3.3 * inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("GRID", (0, 0), (-1, -1), 0, colors.transparent),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("SPAN", (0, 0), (1, 0)),
        ("SPAN", (0, 1), (1, 1)),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.25 * inch))

    # Key metrics strip
    asking = property_details.get("asking_price_display", "N/A")
    rent = property_details.get("estimated_rent_display", "N/A")
    beds = property_details.get("bedrooms", "N/A")
    baths = property_details.get("bathrooms", "N/A")
    sqft = property_details.get("sqft", "N/A")
    year = property_details.get("year_built", "N/A")
    metrics_data = [
        ["Asking Price", "Est. Monthly Rent", "Bed / Bath", "Sq Ft", "Year Built"],
        [asking, rent, f"{beds} / {baths}", str(sqft), str(year)],
    ]
    metrics_table = Table(metrics_data, colWidths=[1.56 * inch] * 5)
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#94a3b8")),
        ("FONTSIZE", (0, 0), (-1, 0), 7.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 1), (-1, 1), WHITE),
        ("FONTSIZE", (0, 1), (-1, 1), 11),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    elements.append(metrics_table)

    # CHANGE 5 -- LangGraph description below the score
    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        "This report was generated by 8 specialist AI agents using the LangGraph framework. "
        "Each agent analyzed one dimension of this property using real public data sources. "
        "See Page 3 for detailed agent reasoning.",
        ParagraphStyle("cover_body", fontSize=10, leading=15, textColor=TEXT_GRAY),
    ))

    elements.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 2: INVESTMENT SCORECARD (with meaning column + key insights)
    # ══════════════════════════════════════════════════════════════════════════
    _page_header(elements, "Investment Scorecard")
    elements.append(Paragraph("Score Breakdown by Agent", s["h2"]))
    _divider(elements)

    # CHANGE 3 -- 5-column table with "What it means"
    score_table_rows = [["Agent", "Score", "Weight", "Contribution", "What it means"]]
    total_contribution = 0.0
    best_row = {"label": "", "score": 0.0, "meaning": ""}
    worst_row = {"label": "", "score": 100.0, "meaning": ""}

    for row in score_rows:
        score_val = float(row.get("score", 0))
        weight_val = float(row.get("weight", 0))
        contribution = float(row.get("weighted_score", score_val * weight_val))
        total_contribution += contribution
        label = row.get("label", row.get("key", ""))
        agent_key = _find_agent_key(label)
        meta = AGENT_META.get(agent_key, {}) if agent_key else {}
        meaning = _score_meaning(score_val, meta) if meta else _score_bracket_label(score_val)

        score_table_rows.append([
            label,
            f"{score_val:.1f}",
            f"{weight_val * 100:.1f}%",
            f"{contribution:.1f}",
            Paragraph(meaning, ParagraphStyle("meaning_cell", fontSize=8, leading=10, textColor=TEXT_DARK)),
        ])

        if score_val >= best_row["score"]:
            best_row = {"label": label, "score": score_val, "meaning": meaning}
        if score_val <= worst_row["score"]:
            worst_row = {"label": label, "score": score_val, "meaning": meaning}

    score_table_rows.append(["OVERALL SCORE", "", "100%", f"{total_contribution:.1f}", ""])

    score_table = Table(score_table_rows, colWidths=[1.8 * inch, 0.8 * inch, 0.8 * inch, 1.0 * inch, 2.5 * inch])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [WHITE, LIGHT_GRAY]),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("ALIGN", (1, 0), (3, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        # Footer row
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, -1), (-1, -1), WHITE),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]
    for i, row in enumerate(score_rows, start=1):
        score_val = float(row.get("score", 0))
        cell_color = _score_color(score_val)
        style_cmds.append(("TEXTCOLOR", (1, i), (1, i), cell_color))
        style_cmds.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))

    score_table.setStyle(TableStyle(style_cmds))
    elements.append(score_table)
    elements.append(Spacer(1, 0.2 * inch))

    # CHANGE 4 -- Key Insights Box
    # Build strongest / weakest / verdict text
    def _insight_text(label: str, score: float, meaning: str) -> str:
        return f"<b>{label}:</b> {score:.1f}/100 -- {meaning}"

    if weighted_total >= 70:
        verdict_text = f"<b>BUY</b> -- Strong overall profile with score {weighted_total:.1f}/100. Multiple positive indicators suggest good investment potential."
    elif weighted_total >= 40:
        verdict_text = f"<b>HOLD</b> -- Mixed signals with score {weighted_total:.1f}/100. Some strengths offset by weaker areas. Consider your risk tolerance."
    else:
        verdict_text = f"<b>PASS</b> -- Score {weighted_total:.1f}/100 indicates significant risks. Multiple agents flagged concerns."

    insight_body = ParagraphStyle("insight_body", fontSize=9, leading=13, textColor=TEXT_DARK)
    insight_label = ParagraphStyle("insight_label", fontSize=9, leading=13, textColor=NAVY, fontName="Helvetica-Bold")

    insights_data = [
        [Paragraph("<b>KEY INSIGHTS</b>", ParagraphStyle("ki_hdr", fontSize=10, textColor=WHITE, fontName="Helvetica-Bold"))],
        [Paragraph(f"<b>STRONGEST FACTOR:</b>  {_insight_text(best_row['label'], best_row['score'], best_row['meaning'])}", insight_body)],
        [Paragraph(f"<b>BIGGEST RISK:</b>  {_insight_text(worst_row['label'], worst_row['score'], worst_row['meaning'])}", insight_body)],
        [Paragraph(f"<b>OVERALL VERDICT:</b>  {verdict_text}", insight_body)],
    ]
    insights_box = Table(insights_data, colWidths=[6.9 * inch])
    insights_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#f0f9ff")),
        ("BOX", (0, 0), (-1, -1), 1.5, NAVY),
        ("LINEBELOW", (0, 1), (-1, 1), 0.5, MID_GRAY),
        ("LINEBELOW", (0, 2), (-1, 2), 0.5, MID_GRAY),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (0, 0), 10),
        ("BOTTOMPADDING", (0, 0), (0, 0), 10),
        ("TOPPADDING", (0, 1), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
    ]))
    elements.append(insights_box)
    elements.append(Spacer(1, 0.15 * inch))

    # Key metrics row -- compute from scores or real data
    elements.append(Paragraph("Key Financial Metrics", s["h2"]))
    _divider(elements)

    # Build scores dict from score_rows for _estimate_metrics
    _scores_dict = {}
    for row in score_rows:
        key = row.get("key", "")
        if key:
            _scores_dict[key] = float(row.get("score", 50))
        # Also try label-based lookup
        agent_key = _find_agent_key(row.get("label", ""))
        if agent_key:
            _scores_dict[agent_key] = float(row.get("score", 50))

    metrics = _estimate_metrics(_scores_dict, property_details)

    kpi_data = [
        ["Gross Rental Yield", "STR (Airbnb) Yield", "LTR Yield", "Est. Annual Return"],
        [metrics["gross_yield"], metrics["str_yield"], metrics["ltr_yield"], metrics["annual_return"]],
    ]
    kpi_table = Table(kpi_data, colWidths=[1.95 * inch] * 4)
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#94a3b8")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 1), (-1, 1), WHITE),
        ("FONTSIZE", (0, 1), (-1, 1), 13),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(kpi_table)

    if metrics["estimated"]:
        elements.append(Spacer(1, 0.05 * inch))
        elements.append(Paragraph(
            "* Yield estimates derived from agent scoring models. "
            "Actual returns depend on purchase price and local rent rates.",
            ParagraphStyle("footnote", fontSize=7.5, leading=10, textColor=TEXT_GRAY, fontName="Helvetica-Oblique"),
        ))

    elements.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 3: AGENT REASONING (NEW)
    # ══════════════════════════════════════════════════════════════════════════
    _page_header(elements, "Agent Reasoning")
    elements.append(Paragraph("Why Each Agent Gave Its Score", s["h2"]))
    elements.append(Paragraph(
        "Each of the 8 specialist agents analyzed one dimension of this property "
        "using real public data sources. Below is the reasoning behind every score.",
        s["body"],
    ))
    elements.append(Spacer(1, 0.1 * inch))

    agent_card_style = ParagraphStyle("agent_card", fontSize=8.5, leading=12, textColor=TEXT_DARK)
    agent_card_bold = ParagraphStyle("agent_card_b", fontSize=8.5, leading=12, textColor=NAVY, fontName="Helvetica-Bold")

    for row in score_rows:
        score_val = float(row.get("score", 0))
        label = row.get("label", row.get("key", ""))
        agent_key = _find_agent_key(label)
        meta = AGENT_META.get(agent_key, {}) if agent_key else {}

        if not meta:
            continue

        sc = _score_color(score_val)
        bracket = _score_bracket_label(score_val)

        # Agent card header
        header_data = [[
            Paragraph(f"<b>{meta['label']}</b>", ParagraphStyle("ah", fontSize=10, textColor=WHITE, fontName="Helvetica-Bold")),
            Paragraph(f"<b>{score_val:.1f}/100</b>", ParagraphStyle("as", fontSize=10, textColor=WHITE, fontName="Helvetica-Bold", alignment=2)),
        ]]
        header_tbl = Table(header_data, colWidths=[5.0 * inch, 1.9 * inch])
        header_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (0, 0), NAVY),
            ("BACKGROUND", (1, 0), (1, 0), sc),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ]))
        elements.append(header_tbl)

        # Agent card body
        body_text = (
            f"<b>DATA SOURCE:</b> {meta['source']}<br/>"
            f"<b>What it measured:</b> {meta['measured']}<br/><br/>"
            f"<b>Score interpretation:</b> Score {score_val:.1f}/100 = {bracket}<br/>"
            f"&nbsp;&nbsp;&nbsp; 0-40: {meta['low']}<br/>"
            f"&nbsp;&nbsp;&nbsp; 41-70: {meta['mid']}<br/>"
            f"&nbsp;&nbsp;&nbsp; 71-100: {meta['high']}<br/><br/>"
            f"<b>Impact:</b> {meta['impact']}"
        )
        body_data = [[Paragraph(body_text, agent_card_style)]]
        body_tbl = Table(body_data, colWidths=[6.9 * inch])
        body_tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
            ("BOX", (0, 0), (-1, -1), 0.5, MID_GRAY),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(body_tbl)
        elements.append(Spacer(1, 0.08 * inch))

    elements.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 4: FULL ANALYSIS REPORT (kept as is)
    # ══════════════════════════════════════════════════════════════════════════
    _page_header(elements, "Full Analysis Report")
    elements.append(Paragraph("AI Investment Report", s["h2"]))
    _divider(elements)
    elements.append(Paragraph(report_text.replace("\n", "<br/>"), s["body"]))
    elements.append(PageBreak())

    # ══════════════════════════════════════════════════════════════════════════
    # PAGE 5: ENVIRONMENTAL + NEIGHBORHOOD + DISCLAIMER (combined)
    # ══════════════════════════════════════════════════════════════════════════
    _page_header(elements, "Environmental, Neighborhood &amp; Legal")

    elements.append(Paragraph("Environmental Summary", s["h2"]))
    _divider(elements)

    aqi_display = property_details.get("aqi_display", "N/A")
    env_data = [
        ["Air Quality (AQI)", aqi_display, "PM2.5", property_details.get("pm25_display", "N/A")],
        ["Flood Zone", property_details.get("flood_zone", "N/A"), "Wildfire Risk", property_details.get("wildfire_display", "N/A")],
        ["Tree Pollen", property_details.get("tree_pollen", "N/A"), "Grass Pollen", property_details.get("grass_pollen", "N/A")],
        ["Heat Days/Year", property_details.get("heat_days", "N/A"), "Insurance", property_details.get("insurance_note", "N/A")],
    ]
    env_table = Table(env_data, colWidths=[1.6 * inch, 2.1 * inch, 1.6 * inch, 2.5 * inch])
    env_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(env_table)
    elements.append(Spacer(1, 0.15 * inch))

    elements.append(Paragraph("Neighborhood Summary", s["h2"]))
    _divider(elements)

    nbr_data = [
        ["School Rating", property_details.get("school_rating", "N/A"), "Crime Index", property_details.get("crime_index", "N/A")],
        ["Walkability", property_details.get("walk_score", "N/A"), "Transit Score", property_details.get("transit_score", "N/A")],
        ["Employment Growth", property_details.get("employment_growth", "N/A"), "Median Income", property_details.get("median_income", "N/A")],
        ["Trajectory", property_details.get("trajectory", "N/A"), "Population", property_details.get("population", "N/A")],
    ]
    nbr_table = Table(nbr_data, colWidths=[1.6 * inch, 2.1 * inch, 1.6 * inch, 2.5 * inch])
    nbr_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(nbr_table)
    elements.append(Spacer(1, 0.15 * inch))

    # Disclaimer section
    elements.append(Paragraph("Important Disclaimers", s["h2"]))
    _divider(elements)
    elements.append(Paragraph(DISCLAIMER, s["body"]))
    elements.append(Spacer(1, 0.15 * inch))

    disclaimer_box_data = [[Paragraph(
        "<b>Data Sources:</b> Zillow ZHVI/ZORI, EPA AirNow, FEMA Flood Maps, "
        "BLS Metropolitan Area Employment, Open Pollen Network, Airbnb Inside.<br/><br/>"
        "<b>AI Engine:</b> LangGraph multi-agent pipeline with GPT-4o-mini coordinator.<br/><br/>"
        "<b>Score Methodology:</b> 8 specialist agents each produce a 0-100 score. "
        "The weighted composite is computed using user-configurable weights. "
        "BUY &ge; 70 | HOLD 40-69 | PASS &lt; 40.",
        s["body"],
    )]]
    disclaimer_box = Table(disclaimer_box_data, colWidths=[6.9 * inch])
    disclaimer_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    elements.append(disclaimer_box)
    elements.append(Spacer(1, 0.25 * inch))

    footer_data = [[
        Paragraph("<b>PropIQ</b> -- Real Estate Intelligence. Unbiased.", ParagraphStyle("ftlogo", fontSize=10, textColor=WHITE, fontName="Helvetica-Bold")),
        Paragraph(f"Generated {gen_date}", ParagraphStyle("ftdate", fontSize=9, textColor=colors.HexColor("#94a3b8"), alignment=2)),
    ]]
    footer_table = Table(footer_data, colWidths=[4.0 * inch, 3.8 * inch])
    footer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(footer_table)

    doc.build(elements)
    return buffer.getvalue()
