from __future__ import annotations

from datetime import datetime
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

NAVY = colors.HexColor("#0f172a")
GREEN = colors.HexColor("#16a34a")
AMBER = colors.HexColor("#d97706")
RED = colors.HexColor("#dc2626")
LIGHT_GRAY = colors.HexColor("#f8fafc")
MID_GRAY = colors.HexColor("#e2e8f0")
TEXT_GRAY = colors.HexColor("#475569")
TEXT_DARK = colors.HexColor("#0f172a")
WHITE = colors.white

DISCLAIMER = (
    "This report was generated by PropIQ using publicly available data from Zillow, EPA AirNow, "
    "BLS, FEMA, and other sources. It is intended for research and informational purposes only "
    "and does not constitute financial, legal, tax, insurance, or investment advice. "
    "Always consult a licensed real estate professional before making investment decisions. "
    "Scores are model-generated estimates and may not reflect current market conditions."
)


def _badge_color(recommendation: str) -> colors.Color:
    if recommendation == "BUY":
        return GREEN
    if recommendation == "HOLD":
        return AMBER
    return RED


def _score_color(score: float) -> colors.Color:
    if score >= 70:
        return GREEN
    if score >= 40:
        return AMBER
    return RED


def _styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle("H1", parent=base["Title"], fontSize=22, textColor=WHITE, leading=28, spaceAfter=4),
        "h2": ParagraphStyle("H2", parent=base["Heading1"], fontSize=14, textColor=NAVY, leading=18, spaceBefore=6, spaceAfter=4),
        "h3": ParagraphStyle("H3", parent=base["Heading2"], fontSize=11, textColor=NAVY, leading=14, spaceBefore=4, spaceAfter=2),
        "body": ParagraphStyle("Body", parent=base["BodyText"], fontSize=9.5, leading=14, textColor=TEXT_DARK),
        "small": ParagraphStyle("Small", parent=base["BodyText"], fontSize=8, leading=11, textColor=TEXT_GRAY),
        "label": ParagraphStyle("Label", parent=base["BodyText"], fontSize=8, leading=10, textColor=TEXT_GRAY, spaceAfter=1),
        "tagline": ParagraphStyle("Tagline", parent=base["BodyText"], fontSize=11, leading=14, textColor=colors.HexColor("#94a3b8")),
        "badge": ParagraphStyle("Badge", parent=base["BodyText"], fontSize=18, leading=22, textColor=WHITE, alignment=1),
        "score_big": ParagraphStyle("ScoreBig", parent=base["Title"], fontSize=42, textColor=WHITE, leading=48, alignment=1),
        "white_body": ParagraphStyle("WhiteBody", parent=base["BodyText"], fontSize=9.5, leading=13, textColor=WHITE),
        "section_label": ParagraphStyle("SLabel", parent=base["BodyText"], fontSize=7.5, leading=10, textColor=TEXT_GRAY, spaceAfter=1, fontName="Helvetica-BoldOblique"),
        "bullet": ParagraphStyle("Bullet", parent=base["BodyText"], fontSize=9.5, leading=14, textColor=TEXT_DARK, leftIndent=12, bulletIndent=0),
    }


def _page_header(elements: list, title: str, subtitle: str = "") -> None:
    header_data = [[Paragraph(f"<b>PropIQ</b>", ParagraphStyle("logo", fontSize=13, textColor=WHITE, fontName="Helvetica-Bold")),
                    Paragraph(title, ParagraphStyle("hdr", fontSize=10, textColor=colors.HexColor("#94a3b8"), alignment=2))]]
    t = Table(header_data, colWidths=[3.5 * inch, 4.3 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.18 * inch))


def _divider(elements: list) -> None:
    elements.append(HRFlowable(width="100%", thickness=1, color=MID_GRAY, spaceAfter=8, spaceBefore=6))


def build_pdf_report(
    property_details: dict[str, Any],
    score_rows: list[dict[str, Any]],
    report_text: str,
    recommendation: str,
    weighted_total: float,
    user_name: str = "PropIQ User",
    generated_at: str | None = None,
) -> bytes:
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.65 * inch,
        rightMargin=0.65 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
    )
    s = _styles()
    address = property_details.get("address") or f"ZIP {property_details.get('zip_code', 'N/A')}"
    zip_code = property_details.get("zip_code", "N/A")
    gen_date = generated_at or datetime.now().strftime("%Y-%m-%d %H:%M")
    badge_color = _badge_color(recommendation)
    score_color = _score_color(weighted_total)

    elements: list[Any] = []

    # ── PAGE 1: COVER ─────────────────────────────────────────────────────────
    cover_top = Table(
        [[Paragraph("<b>PropIQ</b>", ParagraphStyle("clogo", fontSize=20, textColor=WHITE, fontName="Helvetica-Bold")),
          Paragraph("Real Estate Intelligence. Unbiased.", ParagraphStyle("ctagline", fontSize=10, textColor=colors.HexColor("#94a3b8"), alignment=2))]],
        colWidths=[3.5 * inch, 4.3 * inch],
    )
    cover_top.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(cover_top)
    elements.append(Spacer(1, 0.3 * inch))

    # Score hero panel
    score_panel_data = [[
        Paragraph(f"{weighted_total:.1f}", s["score_big"]),
        Paragraph("/100", ParagraphStyle("slash", fontSize=16, textColor=colors.HexColor("#94a3b8"), leading=22, alignment=1)),
        Paragraph(recommendation, ParagraphStyle("rec", fontSize=16, textColor=WHITE, leading=22, fontName="Helvetica-Bold", alignment=1)),
    ]]
    score_panel = Table(score_panel_data, colWidths=[2.5 * inch, 1.0 * inch, 4.3 * inch])
    score_panel.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (1, 0), score_color),
        ("BACKGROUND", (2, 0), (2, 0), badge_color),
        ("TOPPADDING", (0, 0), (-1, -1), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 18),
        ("LEFTPADDING", (0, 0), (-1, -1), 16),
        ("RIGHTPADDING", (0, 0), (-1, -1), 16),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(score_panel)
    elements.append(Spacer(1, 0.25 * inch))

    # Property info box
    info_data = [
        [Paragraph("<b>PROPERTY ADDRESS</b>", s["label"]), ""],
        [Paragraph(address, ParagraphStyle("addr", fontSize=14, textColor=NAVY, fontName="Helvetica-Bold", leading=18)), ""],
        [Paragraph(f"ZIP Code: {zip_code}", s["body"]), Paragraph(f"Analysis Date: {gen_date[:10]}", ParagraphStyle("date", fontSize=9.5, leading=14, textColor=TEXT_DARK, alignment=2))],
        [Paragraph(f"Property Type: {property_details.get('property_type', 'N/A')}", s["body"]),
         Paragraph(f"Generated for: {user_name}", ParagraphStyle("gen", fontSize=9.5, leading=14, textColor=TEXT_DARK, alignment=2))],
    ]
    info_table = Table(info_data, colWidths=[4.5 * inch, 3.3 * inch])
    info_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("GRID", (0, 0), (-1, -1), 0, colors.transparent),
        ("TOPPADDING", (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("SPAN", (0, 0), (1, 0)),
        ("SPAN", (0, 1), (1, 1)),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
    ]))
    elements.append(info_table)
    elements.append(Spacer(1, 0.25 * inch))

    # Key metrics strip
    asking = property_details.get("asking_price_display", "N/A")
    rent = property_details.get("estimated_rent_display", "N/A")
    beds = property_details.get("bedrooms", "N/A")
    baths = property_details.get("bathrooms", "N/A")
    sqft = property_details.get("sqft", "N/A")
    year = property_details.get("year_built", "N/A")
    metrics_data = [
        ["Asking Price", "Est. Monthly Rent", "Bed / Bath", "Sq Ft", "Year Built"],
        [asking, rent, f"{beds} / {baths}", str(sqft), str(year)],
    ]
    metrics_table = Table(metrics_data, colWidths=[1.56 * inch] * 5)
    metrics_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#94a3b8")),
        ("FONTSIZE", (0, 0), (-1, 0), 7.5),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 1), (-1, 1), WHITE),
        ("FONTSIZE", (0, 1), (-1, 1), 11),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 9),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 9),
    ]))
    elements.append(metrics_table)

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(Paragraph(
        "This report was generated using 8 AI specialist agents analyzing price trends, "
        "neighborhood quality, rental yield, 12-month forecast, air quality, pollen, "
        "climate risk, and Airbnb STR viability.",
        ParagraphStyle("cover_body", fontSize=9.5, leading=14, textColor=TEXT_GRAY),
    ))

    elements.append(PageBreak())

    # ── PAGE 2: INVESTMENT SCORECARD ──────────────────────────────────────────
    _page_header(elements, "Investment Scorecard")
    elements.append(Paragraph("Score Breakdown by Agent", s["h2"]))
    _divider(elements)

    score_table_rows = [["Agent", "Score", "Weight", "Contribution"]]
    total_contribution = 0.0
    for row in score_rows:
        score_val = float(row.get("score", 0))
        weight_val = float(row.get("weight", 0))
        contribution = float(row.get("weighted_score", score_val * weight_val))
        total_contribution += contribution
        score_table_rows.append([
            row.get("label", row.get("key", "")),
            f"{score_val:.1f}",
            f"{weight_val * 100:.1f}%",
            f"{contribution:.1f}",
        ])
    score_table_rows.append(["OVERALL SCORE", "", "100%", f"{total_contribution:.1f}"])

    score_table = Table(score_table_rows, colWidths=[3.0 * inch, 1.2 * inch, 1.2 * inch, 1.5 * inch])
    style_cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 1), (-1, -2), [WHITE, LIGHT_GRAY]),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("ALIGN", (1, 0), (-1, -1), "CENTER"),
        # Footer row
        ("BACKGROUND", (0, -1), (-1, -1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, -1), (-1, -1), WHITE),
        ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
    ]
    for i, row in enumerate(score_rows, start=1):
        score_val = float(row.get("score", 0))
        cell_color = _score_color(score_val)
        style_cmds.append(("TEXTCOLOR", (1, i), (1, i), cell_color))
        style_cmds.append(("FONTNAME", (1, i), (1, i), "Helvetica-Bold"))

    score_table.setStyle(TableStyle(style_cmds))
    elements.append(score_table)
    elements.append(Spacer(1, 0.25 * inch))

    # Key metrics row
    elements.append(Paragraph("Key Financial Metrics", s["h2"]))
    _divider(elements)
    str_yield = property_details.get("str_yield_display", "N/A")
    ltr_yield = property_details.get("ltr_yield_display", "N/A")
    annual_return = property_details.get("estimated_return_display", "N/A")
    aqi_display = property_details.get("aqi_display", "N/A")

    kpi_data = [
        ["Gross Rental Yield", "STR (Airbnb) Yield", "LTR Yield", "Est. Annual Return"],
        [ltr_yield, str_yield, ltr_yield, annual_return],
    ]
    kpi_table = Table(kpi_data, colWidths=[1.95 * inch] * 4)
    kpi_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#94a3b8")),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("BACKGROUND", (0, 1), (-1, 1), colors.HexColor("#1e293b")),
        ("TEXTCOLOR", (0, 1), (-1, 1), WHITE),
        ("FONTSIZE", (0, 1), (-1, 1), 13),
        ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    elements.append(kpi_table)
    elements.append(PageBreak())

    # ── PAGE 3: FULL ANALYSIS ─────────────────────────────────────────────────
    _page_header(elements, "Full Analysis Report")
    elements.append(Paragraph("AI Investment Report", s["h2"]))
    _divider(elements)
    elements.append(Paragraph(report_text.replace("\n", "<br/>"), s["body"]))
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Environmental Summary", s["h2"]))
    _divider(elements)

    env_data = [
        ["Air Quality (AQI)", aqi_display, "PM2.5", property_details.get("pm25_display", "N/A")],
        ["Flood Zone", property_details.get("flood_zone", "N/A"), "Wildfire Risk", property_details.get("wildfire_display", "N/A")],
        ["Tree Pollen", property_details.get("tree_pollen", "N/A"), "Grass Pollen", property_details.get("grass_pollen", "N/A")],
        ["Heat Days/Year", property_details.get("heat_days", "N/A"), "Insurance", property_details.get("insurance_note", "N/A")],
    ]
    env_table = Table(env_data, colWidths=[1.6 * inch, 2.1 * inch, 1.6 * inch, 2.5 * inch])
    env_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(env_table)
    elements.append(Spacer(1, 0.2 * inch))

    elements.append(Paragraph("Neighborhood Summary", s["h2"]))
    _divider(elements)

    nbr_data = [
        ["School Rating", property_details.get("school_rating", "N/A"), "Crime Index", property_details.get("crime_index", "N/A")],
        ["Walkability", property_details.get("walk_score", "N/A"), "Transit Score", property_details.get("transit_score", "N/A")],
        ["Employment Growth", property_details.get("employment_growth", "N/A"), "Median Income", property_details.get("median_income", "N/A")],
        ["Trajectory", property_details.get("trajectory", "N/A"), "Population", property_details.get("population", "N/A")],
    ]
    nbr_table = Table(nbr_data, colWidths=[1.6 * inch, 2.1 * inch, 1.6 * inch, 2.5 * inch])
    nbr_table.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.5, MID_GRAY),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_GRAY]),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (2, 0), (2, -1), "Helvetica-Bold"),
        ("TEXTCOLOR", (0, 0), (0, -1), NAVY),
        ("TEXTCOLOR", (2, 0), (2, -1), NAVY),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(nbr_table)
    elements.append(PageBreak())

    # ── PAGE 4: DISCLAIMER ────────────────────────────────────────────────────
    _page_header(elements, "Disclaimer & Legal")

    elements.append(Paragraph("Important Disclaimers", s["h2"]))
    _divider(elements)
    elements.append(Paragraph(DISCLAIMER, s["body"]))
    elements.append(Spacer(1, 0.25 * inch))

    disclaimer_box_data = [[Paragraph(
        "<b>Data Sources:</b> Zillow ZHVI/ZORI, EPA AirNow, FEMA Flood Maps, "
        "BLS Metropolitan Area Employment, Open Pollen Network, Airbnb Inside.<br/><br/>"
        "<b>AI Engine:</b> LangGraph multi-agent pipeline with GPT-4o-mini coordinator.<br/><br/>"
        "<b>Score Methodology:</b> 8 specialist agents each produce a 0–100 score. "
        "The weighted composite is computed using user-configurable weights. "
        "BUY ≥ 70 | HOLD 40–69 | PASS &lt; 40.",
        s["body"],
    )]]
    disclaimer_box = Table(disclaimer_box_data, colWidths=[7.8 * inch])
    disclaimer_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), LIGHT_GRAY),
        ("BOX", (0, 0), (-1, -1), 1, MID_GRAY),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
    ]))
    elements.append(disclaimer_box)
    elements.append(Spacer(1, 0.35 * inch))

    footer_data = [[
        Paragraph("<b>PropIQ</b> -- Real Estate Intelligence. Unbiased.", ParagraphStyle("ftlogo", fontSize=10, textColor=WHITE, fontName="Helvetica-Bold")),
        Paragraph(f"Generated {gen_date}", ParagraphStyle("ftdate", fontSize=9, textColor=colors.HexColor("#94a3b8"), alignment=2)),
    ]]
    footer_table = Table(footer_data, colWidths=[4.0 * inch, 3.8 * inch])
    footer_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING", (0, 0), (-1, -1), 12),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
        ("LEFTPADDING", (0, 0), (-1, -1), 14),
        ("RIGHTPADDING", (0, 0), (-1, -1), 14),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    elements.append(footer_table)

    doc.build(elements)
    return buffer.getvalue()
